inputs:
  port:
    description: 'Specific port for node application to run'
    default: 7001
  environment:
    description: 'Environment for node application to run'
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: Deploy environment
      working-directory: python-env
      run: |
        echo Deployment to ${{ inputs.environment }} has started..
        pm2 delete greetings-app-${{ inputs.environment }} & EXIT /B 0
        pm2 start app.py --name greetings-app-${{ inputs.environment }}" -- --port ${{ inputs.port }}
      shell: cmd